name: Update Github Repository Variable
on:
  workflow_dispatch:

# Ensures that only one workflow per branch will run at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-secrets:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    permissions: write-all
    steps:
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Update Github Secret
        uses: NikhilVashistha/update-github-action-secret@v1.0.3
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          variable: true
          variable_name: 'TEST_VARIABLE'
          variable_value: 'This is working'
